title: Windu
description: > # this means to ignore newlines until "baseurl:"
  Tukang scan.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here


# Author Settings
author: Windu # add your name
author-img: windusasongko.jpg # add your photo
about-author: Maido enthusiast. # add description
social-twitter: becausewhynut_ # add your Twitter handle
social-facebook: winduwindus # add your Facebook handle
social-github: windusasongko # add your Github handle
social-linkedin: windusasongko # add your Linkedin handle
social-email: awindusasongko@gmail.com # add your Email address

# Disqus
discus-identifier: windusasongko # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - gemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
